'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SSA_20171219.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property al() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Deckblatt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Deckblatt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FullVers_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FullVers_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FullVers_KHW_Untersuchung() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FullVers_KHW_Untersuchung", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ls_ab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ls_ab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ls_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ls_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ls_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ls_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nhz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nhz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nutzerkoerper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nutzerkoerper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raeume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raeume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_detailliert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_detailliert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SSA_einfach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SSA_einfach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_58() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_58", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_59() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_59", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_abwKenn_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_abwKenn_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_allgAnw_35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_allgAnw_35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_BeschKlA__49() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_BeschKlA__49", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_BeschKlA_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_BeschKlA_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_BeschKlB_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_BeschKlB_51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_BeschKlC_52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_BeschKlC_52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_BeschKlD_53() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_BeschKlD_53", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_BeschKlE_54() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_BeschKlE_54", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_BeschKlF_55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_BeschKlF_55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_Empf_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_Empf_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_erlEW_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_erlEW_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_Estrich_43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_Estrich_43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_EW_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_EW_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_EW1_57() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_EW1_57", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_EW2_56() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_EW2_56", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_EW3_56_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_EW3_56_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_fremd_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_fremd_30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_HinweiseKat_45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_HinweiseKat_45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_KlasseC_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_KlasseC_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_KlasseD_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_KlasseD_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_KlasseE_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_KlasseE_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_KlasseF_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_KlasseF_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_KMV_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_KMV_41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_LAnlagen_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_LAnlagen_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_LS_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_LS_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_LSAußen_29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_LSAußen_29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_LWasser_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_LWasser_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_Nutzer_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_Nutzer_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_NutzerKoerper_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_NutzerKoerper_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_NutzerKoerper_Prognose_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_NutzerKoerper_Prognose_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_NutzerKoerperAnf_40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_NutzerKoerperAnf_40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_SA_33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_SA_33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_TS_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_TS_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_ungSituation_34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_ungSituation_34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_Wahrnehmbarkeit_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_Wahrnehmbarkeit_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_help_Wasser_27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_help_Wasser_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SSA_Hinweise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SSA_Hinweise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ssa_pfeil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssa_pfeil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ts_bllt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ts_bllt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ts_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ts_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ts_tph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ts_tph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tueren() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tueren", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wasser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wasser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
